global using NUnit.Framework;
global using System.Collections.Concurrent;
global using System.Net;
global using System.Net.Sockets;
global using System.Text;
global using System.Threading;
global using System.Threading.Tasks;
global using McComms.Core;
global using McComms.Sockets;
