// filepath: c:\Code\McComms\src\McComms.WebSockets\GlobalUsings.cs
global using System;
global using System.Net;
global using System.Net.WebSockets;
global using System.Text;
global using System.Text.Json;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Collections.Generic;
global using System.Collections.Concurrent;
global using System.Linq;
global using McComms.Core;
