name: Build and Create NuGet Packages

on:
  # This workflow is triggered on push to main/master branches and on pull request closed events
  push:
    branches: [ main, master ]
    paths:
      - 'src/**'
      - '.github/workflows/**'

  pull_request:
    branches: [ main, master ]
    types: [ closed ]
    paths:
      - 'src/**'
      - '.github/workflows/**'
    
jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET version
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Remove local nuget.config
        run: rm nuget.config || true

      - name: Restore McComms.Core
        run: dotnet restore src/McComms.Core/McComms.Core.csproj

      - name: Build McComms.Core
        run: dotnet build src/McComms.Core/McComms.Core.csproj --configuration Release

      - name: Test McComms.Core
        run: dotnet test src/tests/McComms.Core.Tests/McComms.Core.Tests.csproj --no-build --configuration Release

      - name: Pack McComms.Core
        run: dotnet pack src/McComms.Core/McComms.Core.csproj -o ./src/Packages --configuration Release

      - name: Push McComms.Core to NuGet
        run: dotnet nuget push src/Packages/McComms.Core.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Restore dependencies
        run: dotnet restore McComms.sln

      # - name: Build the solution
      #   run: dotnet build McComms.sln --no-restore --configuration Release

      # - name: List generated packages
      #   run: ls -la src/Packages

      # - name: Test McComms.gRPC
      #   run: dotnet test src/tests/McComms.gRPC.Tests/McComms.gRPC.Tests.csproj --no-build --configuration Release

      # - name: Test McComms.Sockets
      #   run: dotnet test src/tests/McComms.Sockets.Tests/McComms.Sockets.Tests.csproj --no-build --configuration Release

      # - name: Push packages to NuGet.org
      #   if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      #   run: |
      #     for package in src/Packages/*.nupkg; 
      #     do
      #       dotnet nuget push $package --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      #     done
